name: Cypress CI

on:
  push:
    branches:
      - main  # Substitua pela branch que deseja testar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Escolha a versão do Node.js que você está usando

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npm run cypress:run  # Substitua pelo comando que executa seus testes Cypress
